# Generated by Django 3.0 on 2020-02-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(choices=[(True, 'Ordered'), (False, 'Order not confirmed')], default=False),
        ),
    ]
