# Generated by Django 3.0 on 2020-02-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_auto_20200201_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ic', 'In Cart'), ('op', 'Order Placed')], default='In Cart', max_length=50),
        ),
    ]
