# Generated by Django 3.0 on 2020-02-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_auto_20200203_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_filter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
