# Generated by Django 3.0 on 2020-02-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_product_product_price_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='media/images/default.png', null=True, upload_to='images/'),
        ),
    ]
