# Generated by Django 3.0 on 2020-02-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0012_auto_20200206_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='/media/images/default.png', null=True, upload_to='images/'),
        ),
    ]
